# Linguagem Julia

## OPERADORES ARITMÉTICOS

Os operadores aritméticos executam operações matemáticas básicas, como adição e subtração com operandos. Existem dois tipos de operadores matemáticos: unário e binário. Um operador unário executa uma ação com um único operando, já os  um operador binário executa ação com dois operandos. Julia fornece uma coleção completa de operadores aritméticos para as mais diversas expressões de cálculo.


| **Expressão** | **Nome**                              | 
| ------------- | --------------------------------------| 
| +x            | Operador unário de adição             |
| -x            | Operador unário de subtração          | 
| x + y         | Operador binário de adição            | 
| x - y         | Operador binário de subtração         | 
| x * y         | Operador binário de multiplicação     | 
| x / y         | Operador binário de divisão           |
| x ÷ y         | Operador binário de divisão inteira   |
| x \\ y        | Operador binário de divisão esquerda  | 
| x ^ y         | Operador binário de potência          |
| x % y         | Operador binário de resto             |

## CALCULAR O TEMPO DE PROCESSAMENTO

**@time**

A macro `@time` mede o tempo de processamento para executar uma expressão, o número de alocações e o número total de bytes de sua execução.
**@timev**

Esta é uma versão detalhada da macro `@time`, acrescenta:
- elapsed time : tempo de processamento;
- bytes allocated: 
- pool allocs:

**@elapsed**

A macro para avaliar o tempo de processamento para executar uma expressão descartando o valor resultante.

In [5]:
@time sqrt(
    (2*pi + sqrt(log(2569854.5415263))
        /(sin(52)*cos(log(25948.1452))))^100)
    *exp(sin(0.8985424)
)

  0.000100 seconds (18 allocations: 384 bytes)


4.543647706547242

In [2]:
@timev sqrt(
    (2*pi + sqrt(log(2569854.5415263))
        /(sin(52)*cos(log(25948.1452))))^100)
    *exp(sin(0.8985424)
)

  0.000101 seconds (18 allocations: 384 bytes)
elapsed time (ns): 100630
bytes allocated:   384
pool allocs:       18


4.543647706547242

In [3]:
@elapsed sqrt(
    (2*pi + sqrt(log(2569854.5415263))
        /(sin(52)*cos(log(25948.1452))))^100)
    *exp(sin(0.8985424)
)

7.6182e-5

## FUNÇÕES DE IMPRESSÃO

**Função print() ou println()**

Escreve (para o fluxo de saída padrão) uma representação textual ou um valor se houver. A representação usada pelo comando inclui formatação mínima.

**Comando display**

Semelhante à função `print()`, utiliza recursos mais elaborados de visualização. É excelente para imprimir na tela o resultado de várias expressões em linhas.

**Macro @show()**

É uma macro que exibe a expressão e o resultado do cálculo.

In [6]:
print(sind(45))

0.7071067811865476

In [7]:
display(sind(45))

0.7071067811865476

In [8]:
@show sind(45)

sind(45) = 0.7071067811865476


0.7071067811865476

## Tipos de Dados

Em `Julia` existem basicamente dois tipos: tipos abstratos e tipos concretos. Um tipo abstrato é caracterizado por não ser instanciado, servindo apenas para a construção de outros tipos. Já os tipos concretos podem ser instanciados, mas não podem ter subtipos. A árvore de tipo da linguagem `Julia` é bem extensa porém útil, pois permite a construção de código optimizados de acordo com a aplicação.

**Dados mutáveis x dados imutáveis**

<img src="Figuras/tipos-arvore-julia.png" align="center" width="500">

<center>Fonte: (TOAL et al, 2017)</center>

### NÚMEROS INTEIROS:

São definidos como tipos inteiros os dados numéricos, não racionais, positivos ou negativos. Podem ser representados sem sinal(`unsigned`) ou com sinal (`signed`) capaz de representar números negativos.

<table cellspacing="2" cellpadding="2">
<tbody>
<tr>
<th>
<p>Tipo</p>
</th>
<th>
<p>Número de Bits</p>
</th>
<th>
<p>Menor Valor</p>
</th>
<th>Maior Valor</th>
</tr>
<tr>
<td>
<p>Int8</p>
</td>
<td>
<p>8</p>
</td>
<td>
<p>$-2^7$</p>
</td>
<td>
<p>$2^7 - 1$</p>
</td>
</tr>
<tr>
<td>
<p>UInt8</p>
</td>
<td>
<p>8</p>
</td>
<td>
<p>0</p>
</td>
<td>
<p>$2^8 - 1$</p>
</td>
</tr>
<tr>
<td>
<p>Int16</p>
</td>
<td>
<p>16</p>
</td>
<td>
<p>$-2^{15}$</p>
</td>
<td>
<p>$2^{15} - 1$</p>
</td>
</tr>
<tr>
<td>
<p>UInt16</p>
</td>
<td>
<p>16</p>
</td>
<td>
<p>0</p>
</td>
<td>
<p>$2^{16} - 1$</p>
</td>
</tr>
<tr>
<td>
<p>Int32</p>
</td>
<td>
<p>32</p>
</td>
<td>
<p>$-2^{31}$</p>
</td>
<td>
<p>$2^{31} - 1$</p>
</td>
</tr>
<tr>
<td>
<p>UInt32</p>
</td>
<td>
<p>32</p>
</td>
<td>
<p>0</p>
</td>
<td>
<p>$2^{32} - 1$</p>
</td>
</tr>
<tr>
<td>
<p>Int64</p>
</td>
<td>
<p>64</p>
</td>
<td>
<p>$-2^{63}$</p>
</td>
<td>
<p>$2^{63} - 1$</p>
</td>
</tr>
<tr>
<td>
<p>UInt64</p>
</td>
<td>
<p>64</p>
</td>
<td>
<p>0</p>
</td>
<td>
<p>$2^{64} - 1$</p>
</td>
</tr>
<tr>
<td>
<p>Int128</p>
</td>
<td>
<p>128</p>
</td>
<td>
<p>$-2^{127}$</p>
</td>
<td>
<p>$2^{127} - 1$</p>
</td>
</tr>
<tr>
<td>
<p>UInt128</p>
</td>
<td>
<p>128</p>
</td>
<td>
<p>0</p>
</td>
<td>
<p>$2^{128} - 1$</p>
</td>
</tr>
<tr>
<td>
<p>Bool</p>
</td>
<td>
<p>8</p>
</td>
<td>
<p>false(0)</p>
</td>
<td>
<p>true(1)</p>
</td>
</tr>
</tbody>
</table>



###  PONTO FLUTUANTE:

Os números de ponto flutuante na linguagem Julia seguem o padrão IEEE 754, definido como:

$$SM * 2^E$$
$S$ é o sinal, $M$ é a mantissa ou parte fracionária, 2 é a base (binário) e $E$ é o expoente. A tabela abaixo contém 

<table width="250" cellspacing="0" cellpadding="2">
<tbody>
<tr>
<th width="63">
<p>Tipo</p>
</th>
<th width="66">
<p>Precisão</p>
</th>
<th width="108">Número de Bits</th>
</tr>
<tr>
<td width="63">
<p><code>Float16</code></p>
</td>
<td width="66">
<p>half</p>
</td>
<td width="108">
<p>16</p>
</td>
</tr>
<tr>
<td width="63">
<p><code>Float32</code></p>
</td>
<td width="66">
<p>single</p>
</td>
<td width="108">
<p>32</p>
</td>
</tr>
<tr>
<td width="63">
<p><code>Float64</code></p>
</td>
<td width="66">
<p>double</p>
</td>
<td width="108">
<p>64</p>
</td>
</tr>
</tbody>
</table>

### TIPOS RACIONAIS:

Julia tem um tipo específico para representar números racionais construídos usando o operador `//`. Os números racionais são úteis quando é necessário representar proporções exatas de inteiros composto por numerador e denominador, eliminando dessa forma problemas de arredondamento.

Exemplo: representar $ \displaystyle {1 \over 3} + {7 \over 7} $

In [11]:
1//3 + 7//3

8//3

Quando ocorre uma operação de um racional com um inteiro, Julia normaliza para um denominador comum. No caso de um tipo flutuante o racional é convertido para flutuante.

In [12]:
1//3 + 2

7//3

## VARIÁVEIS E CONSTANTES


Em função da tipagem dinâmica de , uma variável pode alterar o tipo em tempo de execução conforme o valor atribuído. Os nomes das variáveis são `case-sensitive` (há diferença entre nomes com letras maiúsculas e minúsculas) e devem começar com uma letra (A-Z ou a-z). Variáveis locais e globais. Variáveis globais ..... . Variáveis locais.... . De acordo com Benzason et all (2015) é difícil para o compilador otimizar o código envolvendo variáveis globais, já que seus valores (ou até mesmo seus tipos) podem mudar a qualquer momento. Declarar uma variável global como `const` resolve esse problema de desempenho.

In [13]:
# Atribindo o valor 2 a variavel x
x = 2
# Executando o cálculo
x^2

4

**`'INPUT'` de dados**

A função `readlines()` permite ler caracteres digitados.

In [17]:
println("Digite numero A :")
a = readline()

println("Digite numero B :")
b = readline()

println("Resultado da operação mod entre $a e $b: ", mod(Meta.parse(a), Meta.parse(b)))

Digite numero A :
stdin> 10
Digite numero B :
stdin> 3
Resultado da operação mod entre 10 e 3: 1


In [18]:
# Declarando várias variáveis
x = 5 ; y = 10 ; z = "julia";

In [19]:
# Variáveis criadas
# Para ver todas as variáveis globais criadas.
varinfo()

| name        |     size | summary |
|:----------- | --------:|:------- |
| Base        |          | Module  |
| Core        |          | Module  |
| Main        |          | Module  |
| a           | 10 bytes | String  |
| b           |  9 bytes | String  |
| startupfile | 55 bytes | String  |
| x           |  8 bytes | Int64   |
| y           |  8 bytes | Int64   |
| z           | 13 bytes | String  |


## CONSTANTES

A declaração `const` é útil para variáveis globais, especialmente porque é difícil para o compilador otimizar o código envolvendo variáveis globais, já que seus valores (ou até mesmo seus tipos) podem mudar a qualquer momento. Utilizar constantes declaradas como `const` resolve o problema e melhora o desempenho. 

In [27]:
π, ℯ

(π = 3.1415926535897..., ℯ = 2.7182818284590...)

## STRING
Uma string é uma sequencia de um ou vários caracteres escritos entre aspas duplas. Quando trabalhamos com céluas do IPython/Jupyter do tipo `Markdown` e temos uma palavara que necessita dos caractes `#, % e *` ,  é necessário acrescentar a barra invertida antes dos caractere  (ex: `\#`) para não ocorrer variação de formatação do texto. A linguagem `Julia` suporta caracteres Unicode e UTF-8. O site https://unicode-table.com/pt/ oferece várias tabelas de caractes em Unicode. Sintaxe:
```julia
nome_string = "s t r i n g"
               1 2 3 4 5 6 -> índice
nome_string[i]
```
Sendo: 
* **i**: índice da posição da sequencia string.

## TUPLA

Tupla é uma sequência ordenada de elementos entre pararênteses semelhante a um vetor. A principal diferença entre arrays e tuplas é que tuplas são **imutáveis** ou seja, uma vez definido os elementos não é possível modificar o valor ou tipo do conteúdo. Tuplas são utilizadas quando é necessário representar dados que não devem ser modificados, pois dessa forma é garantido a integridade dos dados e assegurando que até o programador ou um bug não consigam modificar sua estrutura. Na linguagem `Julia` as tuplas são utilizadas com muita frequencia para expressar listas de argumentos e para retornar múltiplos valores de funções. Sintaxe:
```julia
(elemento_1, elemento_2, ..., elemento_n)
```
E o tipo pode ser inteiro, float, complex e outros.

In [31]:
t1 = (1, 2, "3") ; t2 = (5, 8, 9.0);
typeof(t1), typeof(t2)

(Tuple{Int64,Int64,String}, Tuple{Int64,Int64,Float64})

## ARRAY, LISTAS, VETORES E MATRIZES
Um `array` é uma coleção ordenada de elementos da seguinte forma:
```julia
quantidade_elementos Array{Tipo,dimensão}
```
Na linguagem `Julia`, os arrays são usados para listas, vetores, tabelas e matrizes. Um `array` unidimensional atua como um vector ou uma lista. Uma `array` bidimensional pode ser utilizada como uma tabela ou matriz.

Vetor coluna:

In [2]:
v_col1 = [1, 2, 3, 4, 5, 6, 7]

# ou 
v_col2 = ["a";"b";"c";"d";"e"]

display(v_col1)
display(v_col2)

7-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7

5-element Array{String,1}:
 "a"
 "b"
 "c"
 "d"
 "e"

Vetor Linha. Vetores linha são bidimensionais `Array{Tipo_dado,2}`.


In [3]:
v_lin1 = [1 2 3 4 5]

1×5 Array{Int64,2}:
 1  2  3  4  5

In [4]:
# dimensoes do vetor
@show ndims(v_col1)
@show ndims(v_col2) 
@show ndims(v_lin1)

ndims(v_col1) = 1
ndims(v_col2) = 1
ndims(v_lin1) = 2


2

Comprimento de um vetor:

In [6]:
length(v_col1) , length(v_col2), length(v_lin1)

(7, 5, 5)

#### MANIPULAÇÃO DE VETORES/ARRAYS

Muitos dos comandos abaixo não funcionam para vetores linha.

In [43]:
a = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

Adicionando o elementos ao final do vetor:

In [44]:
push!(a,10)

4-element Array{Int64,1}:
  1
  2
  3
 10

In [45]:
append!(a,11)

5-element Array{Int64,1}:
  1
  2
  3
 10
 11

Adicionando o elementos no inicio do vetor:

In [46]:
prepend!(a, -1)

6-element Array{Int64,1}:
 -1
  1
  2
  3
 10
 11

Para retirar elemento do vetor.
Para remover do final:
```julia
pop!(vetor)
```
Para remover do inicio:
```julia
popfirst!(vetor)
```
Para remover de qualquer posição:
```julia
deleteat!(vetor, posicao)
```

In [47]:
@show pop!(a)
@show popfirst!(a)
@show deleteat!(a, 4)

pop!(a) = 11
popfirst!(a) = -1
deleteat!(a, 4) = [1, 2, 3]


3-element Array{Int64,1}:
 1
 2
 3

#### CRIAÇÃO E ACESSO A ELEMENTOS DE MATRIZES

Matrizes são formadas por vetores linhas (matriz 1xn) e a índice dos elementos segue a lógica de 1 a n (quantidade de elementos) lidos de cima para baixo, coluna por coluna. Sintaxe:
```julia
[elemento_1_1  elemento_1_2 ... ; elemento_2_1  elemento_2_2...; elemento_n_1  ...  elemento_n_m]
```
Para acessar elementos de uma matriz temos a sintaxe:
```julia
matriz[linha, coluna]
```

In [49]:
#Criando uma matriz
Ma = [2 4 6 ; 8 9 10 ; 12 14 15]

3×3 Array{Int64,2}:
  2   4   6
  8   9  10
 12  14  15

In [51]:
Ma2 = Ma*2

3×3 Array{Int64,2}:
  4   8  12
 16  18  20
 24  28  30

In [53]:
Ma * Ma2

3×3 Array{Int64,2}:
 216  256  284
 416  506  576
 632  768  874

In [60]:
Ma + Ma2

3×3 Array{Int64,2}:
  6  12  18
 24  27  30
 36  42  45

In [63]:
[1, 2, 3] * [2 3 4]

3×3 Array{Int64,2}:
 2  3   4
 4  6   8
 6  9  12



## OPERADORES RELACIONAIS

Operadores relacionais são utilizados para comparar valores de expressões simples ou compostas, resultado em um valor lógico VERDADEIRO ou FALSO. 
<table aling="center">
	<thead>
		<tr>
			<th>Operador</th>
			<th>Nome</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td> == </td>
			<td>Igual a </td>
		</tr>
		<tr>
			<td>=!</td>
			<td>Diferente</td>
		</tr>
		<tr>
			<td> > </td>
			<td>maior que</td>
		</tr>
		<tr>
			<td> < </td>
			<td>menor que</td>
		</tr>
        <tr>
			<td> >= </td>
			<td>maior igual</td>
		</tr>
        <tr>
			<td> <= </td>
			<td>menor igual</td>
		</tr>
	</tbody>
</table>

* `isequal(x, y)`  , verdadeiro se x e y são idêntico
* `isfinite(x)`	   , verdadeiro se x é um número infinito 
* `isinf(x)`       , verdadeiro se x é infinito (inf)
* `isnan(x)`       , x não é um número

## OPERADORES LÓGIGOS 

Operadores lógicos são utilizados para criar operações lógicas mais complexas resultado em um valor lógico. O valor de uma expressão lógica é ou VERDADEIRO ou FALSO. Principais operadores lógicos: 

| Expressão  | Nome                          |
| ---------- | ------------------------------|
| `~x`       | Negação                       |
| `x & y`    | E                             |
| `x | y`    | OU                            |
| `x ⊻ y`    | Ou exclusivo                  |
| `x >>> y`  | deslocamento para a direita   |
| `x >> y`   | arithmetic shift right        |
| `x << y`   | logical/arithmetic shift left |

Uma expressão booleana é verdadeira se o resultado do cálculo das combinações lógicas das expressões booleanas for verdadeiro.

## EXPRESSÕES COMPOSTAS

Uma expressão composta avalia várias subexpressões em ordem e retorna o valor da última subexpressão. Sintaxe:
```julia
variável = begin
    expressão_1
    expressão_2
    ...
    expressão_n
end
```
ou
```julia
variável = (expressão_1; expressão_2;...;expressão_n)
```

In [39]:
# Por padrão, será impresso somente a ultima linha, mas as variáveis internas são acessíveis
x = begin
    a = 5
    b = 4
    c = -2
    
    d = b^2 - 4*a*c
    
    [(-b + sqrt(d))/2*a, (-b - sqrt(d))/2*a]
end
y = (a = 1; b = 4; c = -2; d = b^2 - 4*a*c; [(-b + sqrt(d))/2*a, (-b - sqrt(d))/2*a])
x,y

([8.70829, -28.7083], [0.44949, -4.44949])


## ESTRUTURAS DE CONTROLE CONDICIONAIS

 As estruturas condional ou de seleção, são utilizadas para selecionar quais fluxos de dados serão executados durante a execução de um código. Na linguagem Julia temos as estruturas `if` e opcionalmente `switch`.
 
 ### CONDICIONAL "IF" (SE)

A função  `sleep(tempo_segundos)` permite controlar o laço em um determinado tempo em segundos. Sintaxe Básica:

```julia
if condição                   if condição                if condição
   instruções                    instruções                 instruções
end                           else                       elseif
                                 instruções                 instruções
                              end                        elseif
                                                            ...
                                                         else
                                                             instruções
                                                         end
                              
```

### CONDICIONAL "TROCAR" (SWITCH) 

Não existe um comando nativo para "case" ou "swith" na linguagem `Julia`. Pode ser utilizado uma sequencia de `if...elseif...else...end`. 

### OPERADOR TERNÁRIO

O operador ternário **(:?)** está relacionado com a sintaxe `if-elseif-else` e recebe este nome em função de ser o único operador na maioria das linguagens que tomam três operandos: 

```julia
condição ? expressão_1 : expressão_2
```

A operação ternária efeturá a **"expressão1"** antes do **":"**    se a **"condição"** é verdadeira ou a **"expressão_2"** depois do **":"** se **condição** for falsa. 

## AVALIAÇÃO DE CURTO CIRCUITO

* A subexpressão `B` só é avaliada se a subexpressão `A` for verdadeira:

```julia
A && B
```
* A subexpressão `B` só é avaliada se a subexpressão `A` for falsa:

```julia
A || B
```


In [84]:
curto(x::Bool, nome::String)= x ? (println("passou por ", nome); true) : false
if curto(false, "a1") && curto(true, "b1")
    println("entrou no primeiro if")
end
if curto(true, "a2") && curto(false, "b2")
    println("entrou no segundo if")
end
if curto(true, "a3") && curto(true, "b3")
    println("entrou no terceiro if")
end

passou por a2
passou por a3
passou por b3
entrou no terceiro if


## ESTRUTURAS DE CONTROLE DE REPETIÇÃO

Julia possui as estruturas de repetição `for, while` e `do`. 

### REPETIÇÃO "FOR" 

Em um laço de repetição `for`, a execução de uma ou grupo de instruções é repetida várias vezes de forma consecutiva até o limite definido por um elemento sequencial. A função  `sleep(tempo_segundos)` permite controlar o tempo do laço em segundos.

Sintaxe Básica:
```julia
for variável = / in coleção
    instruções
end
```
Sendo: 
* **coleção**: lista, vetor, matriz, dicionário ou conjunto.

**Break e Continue**

O comando `break` interrompe o loop imediatamente quando uma condição é satisfeita. O comando `continue` interrompe a iteração atual do loop e passa para a próxima iteração.
Sintaxe:
```julia
for variável = coleção # pode ser variável in 
    condição variável
        continue/break
    end
end
```

### REPETIÇÃO "ENQUANTO" (WHILE)

O comando `while` permite que uma parte do código seja executado enquanto uma determinada condição for verdadeira. A função  `sleep(tempo_segundos)` permite controlar o laço em um determinado tempo em segundos.
Sintaxe Básica:
```julia
while condição 
    instruções
end
```

### REPETIÇÃO DO

Sintaxe Básica:
```julia
função do variável
  instruções
end
```

In [40]:
# findall retorna o indice do vetor quando encontrar o valor igual a 5
x = 1:0.1:20

findall(x) do x
    x == 5     
end


1-element Array{Int64,1}:
 41

In [41]:
x[41]

5.0

### FUNÇÕES GENÉRICAS 

As funções genéricas são chamadas assim porque estão prontas para trabalhar com diferentes tipos de dados para suas variáveis. Dessa forma, será retornado o valor processador da ultima linha da função. Assim, quando temos uma função contendo várias expressões, devemos utilizar o comando `return` para explicitar qual linha retornará o valor que desejamos trabalhar fora da função. É possível ainda definir o tipo de dado do retorno calculado pela função. Sintaxe:

Sintaxe:

```julia
function nome(argumento_1, argumento_2..., argumento_n)
    expressão_1
    expressão_2
    ...
    expressão_n
    return valor_1, valor_2, ...., valor_n
end
```
Há ainda uma forma reduzida da função genérica bem semelhante a uma função matemática, definida como:

```julia
nome_função(argumento_1, argumento_2..., argumento_n)  = expressão_1, expressão_2, ..., expressão_n
```
Ainda podemos utilizar a forma reduzida com várias linhas na forma:
```julia
nome_função(argumento_1, argumento_2..., argumento_n) = begin
    expressão_1
    expressão_2
    ...
    expressão_n
    return valor_1, valor_2, ...., valor_n
end
```
O resultado de uma constante aplicado a uma função é uma constante e o resultado de um vetor ou matriz aplicado a uma função corresponde a um resultado na forma de vetor ou matriz.

In [43]:
# forma tradicional.
function f1(x)
    x^2 + 2*x + 1
end
f1(5)

36

In [44]:
# forma reduzida
f2(x) = x^2 + 2*x + 1
f2(5)

36

In [46]:
# Retorno Tupla
function f3(x)
    x^2 , x/2
end

f3 (generic function with 1 method)

#### BROADCASTING

A função `broadcast(f, coleção)` aplica uma função `f` sobre uma coleção retornando outra coleção de resultados processados. Dessa forma é posível utilizar vetores, matrizes, conjuntos e tuplas como argumento de uma função no qual a será processado cada elemento da coleção. A sintaxe `f.(coleção)` é equivalente à `broadcast(f, coleção)`. Dicionários e tuplas nomeadas não podem ser utilizadas como argumento.

In [47]:
#Vetor
broadcast(f2, [2, 3, 4])

3-element Array{Int64,1}:
  9
 16
 25

In [48]:
# Vetor
f2.([2, 3, 4])

3-element Array{Int64,1}:
  9
 16
 25